name: Run Tests and Deploy

on:
  push:
    branches:
      - main # Adjust this based on your branch names

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clear known_hosts file
        run: rm -f ~/.ssh/known_hosts

      - name: Clear known hosts
        run: ssh-keygen -R 159.223.10.226

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.6"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest selenium
      # - name: Install dependencies
      #   run: |
      #     pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Show contents of PRIVATE_KEY
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY"  # Output the contents of the private key for verification

      - name: Create deploy_key.pem and verify permissions
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          ls -l deploy_key.pem  # Check file permissions

      - name: Show contents of deploy_key.pem
        run: cat deploy_key.pem

      - name: Use SSH key to connect to server
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -i deploy_key.pem root@159.223.10.226 "cd /home/"
