name: Run Tests and Deploy

on:
  push:
    branches:
      - main # Adjust this based on your branch names

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.6" # Specify Python version

      # - name: Install dependencies
      #   run: |
      #     pip install -r requirements.txt

      - name: Run tests
        run: pytest

      #  >>>>>>>> then

      - name: Deploy to VPS
        if: ${{ steps.test.outcome == 'success' }}
        run: |
          # Add your deployment commands here to transfer code to your VPS
