name: Run Tests and Deploy

on:
  push:
    branches:
      - main # Adjust this based on your branch names

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clear known_hosts file
        run: rm -f ~/.ssh/known_hosts

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.6"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask
          pip install pytest

      - name: Run tests
        run: pytest

      - name: Use SSH key to connect to server and deploy
        run: |
          echo "$PRIVATE_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh -o StrictHostKeyChecking=no -i deploy_key.pem root@159.223.10.226 "cd /home/farm/ && git pull origin main && systemctl restart farm"
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
