name: Run Tests and Deploy

on:
  push:
    branches:
      - main # Adjust this based on your branch names

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.6"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest selenium
      # - name: Install dependencies
      #   run: |
      #     pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Deploy to VPS
        if: ${{ steps.test.outcome == 'success' }}
        run: |
          echo "$SSH_PRIVATE_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh -i deploy_key.pem root@159.223.10.226 "cd /home/"
